a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
c=int(input("Enter the value of c:"))
root1=((-b)+(((b**2)-(4*a*c))**0.5))/(2*a)
root2=((-b)-(((b**2)-(4*a*c))**0.5))/(2*a)
print(root1)
print(root2)